/* ==========================================================================
   WAVENEXA — Shopify Headless Configuration
   Connects your custom storefront to the official Shopify "Headless" app.
   ========================================================================== */

(function () {
  const DEFAULT_CONFIG = {
    // 1. Your myshopify store domain (from your Shopify admin URL)
    storeDomain: 'fashion-hub-215153474.myshopify.com',

    // 2. Storefront API Access Token generated by the "Headless" sales channel/app in Shopify Admin
    storefrontAccessToken: '8a0e809d4e8636eb5c4d0f48474de405',

    // 3. Shopify Storefront API version
    apiVersion: '2024-10',

    // 4. Link to your Shopify Admin Portal for managing products, orders & inventory
    adminUrl: 'https://admin.shopify.com/store/fashion-hub-215153474',

    // 5. Default currency formatting
    currencyCode: 'INR',
    currencySymbol: '₹',

    // 7. Automatic redirect to Shopify Checkout
    autoShopifyCheckout: true
  };

  // Read saved config overrides from localStorage (if updated via UI)
  function loadConfig() {
    try {
      const saved = localStorage.getItem('tc_shopify_config');
      if (saved) {
        const parsed = JSON.parse(saved);
        // Clear obsolete previous token if present in localStorage
        if (parsed.storefrontAccessToken === '8b5977817c4e04499c4821bb16c89ad2') {
          parsed.storefrontAccessToken = DEFAULT_CONFIG.storefrontAccessToken;
          try {
            localStorage.setItem('tc_shopify_config', JSON.stringify(parsed));
          } catch (_) {}
        }
        if (parsed.storeDomain && parsed.storeDomain.includes('fashion-hub') && parsed.storefrontAccessToken && !parsed.storefrontAccessToken.includes('PASTE_YOUR_')) {
          return Object.assign({}, DEFAULT_CONFIG, parsed);
        }
      }
    } catch (e) {
      console.warn('[Shopify Config] Failed to load from storage:', e);
    }
    return Object.assign({}, DEFAULT_CONFIG);
  }

  // Global config object
  window.ShopifyConfig = loadConfig();

  // Check if live Shopify credentials are provided
  window.isShopifyConfigured = function () {
    const cfg = window.ShopifyConfig;
    if (!cfg || !cfg.storeDomain || !cfg.storefrontAccessToken) return false;
    const isPlaceholderDomain = cfg.storeDomain.includes('your-store-name') || cfg.storeDomain.includes('your-brand');
    const isPlaceholderToken = cfg.storefrontAccessToken.includes('PASTE_YOUR_') || cfg.storefrontAccessToken.length < 10;
    return !isPlaceholderDomain && !isPlaceholderToken;
  };

  // Get dynamic Shopify Admin URL for the configured store
  window.getShopifyAdminUrl = function () {
    const cfg = window.ShopifyConfig;
    if (cfg && cfg.storeDomain && !cfg.storeDomain.includes('your-store-name')) {
      const clean = cfg.storeDomain.replace(/^https?:\/\//, '').replace(/\/.*$/, '').trim();
      const shopSlug = clean.replace('.myshopify.com', '');
      return `https://admin.shopify.com/store/${shopSlug}`;
    }
    return cfg?.adminUrl || 'https://admin.shopify.com';
  };

  // Save new config at runtime (e.g. from the admin connection modal)
  window.saveShopifyConfig = function (updates) {
    const current = loadConfig();
    const updated = Object.assign({}, current, updates);

    // Normalize domain
    if (updated.storeDomain) {
      updated.storeDomain = updated.storeDomain
        .replace(/^https?:\/\//, '')
        .replace(/\/.*$/, '')
        .trim();
      if (!updated.storeDomain.includes('.myshopify.com') && !updated.storeDomain.includes('.')) {
        updated.storeDomain += '.myshopify.com';
      }
      const shopSlug = updated.storeDomain.replace('.myshopify.com', '');
      updated.adminUrl = `https://admin.shopify.com/store/${shopSlug}`;
    }

    if (updated.storefrontAccessToken) {
      updated.storefrontAccessToken = updated.storefrontAccessToken.trim();
    }

    localStorage.setItem('tc_shopify_config', JSON.stringify(updated));
    window.ShopifyConfig = updated;
    window.dispatchEvent(new CustomEvent('shopifyConfigUpdated', { detail: updated }));
    return updated;
  };
})();
